/* Generated by AN DISI Unibo */ 
package it.unibo.ctxDomainModel;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxDomainModel  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxDomainModel";
	return QActorContext.initQActorSystem(
		"ctxdomainmodel", "./srcMore/it/unibo/ctxDomainModel/mengoli.pl", 
		"./srcMore/it/unibo/ctxDomainModel/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	initTheContext();
} 	
}
