/* Generated by AN DISI Unibo */ 
package it.unibo.ctxCamera;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxCamera  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxCamera";
	return QActorContext.initQActorSystem(
		"ctxcamera", "./srcMore/it/unibo/ctxCamera/cameraprova.pl", 
		"./srcMore/it/unibo/ctxCamera/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	initTheContext();
} 	
}
