/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.led;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Led extends AbstractLed { 
	public Led(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
