/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.obstaclesonar;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Obstaclesonar extends AbstractObstaclesonar { 
	public Obstaclesonar(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
