/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.logic_controller;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Logic_controller extends AbstractLogic_controller { 
	public Logic_controller(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
