/* Generated by AN DISI Unibo */ 
package it.unibo.ctxModel;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxModel  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxModel";
	return QActorContext.initQActorSystem(
		"ctxmodel", "./srcMore/it/unibo/ctxModel/mengoli.pl", 
		"./srcMore/it/unibo/ctxModel/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	initTheContext();
} 	
}
