/* Generated by AN DISI Unibo */ 
package it.unibo.ctxControl;
import it.unibo.qactors.QActorContext;
import java.io.InputStream;
import alice.tuprolog.SolveInfo;
import alice.tuprolog.Term;
import alice.tuprolog.Var;
 
import it.unibo.is.interfaces.IBasicEnvAwt;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;

public class MainCtxControl   {
private IBasicEnvAwt env; 
private it.unibo.qactor.robot.RobotActor robot; 
 
 	
/*
* ----------------------------------------------
* MAIN
* ----------------------------------------------
*/
 
	public static void main(String[] args) throws Exception{
			IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
			it.unibo.qactors.QActorUtils.setRobotBase("nano2" );  
		    String webDir = null;
			QActorContext.initQActorSystem(
				"ctxcontrol", "./srcMore/it/unibo/ctxControl/mengoli.pl", 
				"./srcMore/it/unibo/ctxControl/sysRules.pl", outEnvView,webDir, false);
 	}
 	
}
