/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.control;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Control extends AbstractControl { 
	public Control(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
