/* Generated by AN DISI Unibo */ 
package it.unibo.ctxModel;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Control_evh extends AbstractControl_evh { 
	public Control_evh(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
