/* Generated by AN DISI Unibo */ 
package it.unibo.ctxLogicRobot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evh_logicrobot extends AbstractEvh_logicrobot { 
	public Evh_logicrobot(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
