/* Generated by AN DISI Unibo */ 
package it.unibo.logic_controller;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.ActorTerminationMessage;
import it.unibo.qactors.QActorMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.ActionReceiveTimed;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;


//REGENERATE AKKA: QActor instead QActorPlanned
public abstract class AbstractLogic_controller extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	//protected IMsgQueue mysupport ;  //defined in QActor
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction  action;
	
			protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
				return outEnvView;
			}
	
	
		public AbstractLogic_controller(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/logic_controller/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/logic_controller/plans.txt";
			//Plan interpretation is done in Prolog
			//if(planFilePath != null) planUtils.buildPlanTable(planFilePath);
	 	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name );
	 		initSensorSystem();
			boolean res = init();
			//println(getName() + " doJob " + res );
		} 
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/
	    public boolean init() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "init";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = "\"filter init\"";
	    		println( temporaryStr );  
	    		parg = "loadTheory(\"./extendedWorldTheory.pl\")";
	    		//tout=1 day (24 h)
	    		//aar = solveGoalReactive(parg,86400000,"","");
	    		//genCheckAar(m.name)»		
	    		QActorUtils.solveGoal(parg,pengine );
	    		if( ! planUtils.switchToPlan("waitForNumSonars").getGoon() ) break;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=init WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean waitForNumSonars() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "waitForNumSonars";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = "\"waiting for sensors\"";
	    		println( temporaryStr );  
	    		//senseEvent
	    		timeoutval = 600000;
	    		aar = planUtils.senseEvents( timeoutval,"numOfSonars","continue",
	    		"" , "",ActionExecMode.synch );
	    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
	    			//println("			WARNING: sense timeout");
	    			addRule("tout(senseevent,"+getName()+")");
	    			//break;
	    		}
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?msg(E,\"event\",S,none,numOfSonars(N),F)" )) != null ){
	    		temporaryStr = "numOfSonars(N)";
	    		temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    		println( temporaryStr );  
	    		}
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??msg(E,\"event\",S,none,numOfSonars(N),F)" )) != null ){
	    		parg = "assert(numofsonars(N))";
	    		parg = QActorUtils.substituteVars(guardVars,parg);
	    		//tout=1 day (24 h)
	    		//aar = solveGoalReactive(parg,86400000,"","");
	    		//genCheckAar(m.name)»		
	    		QActorUtils.solveGoal(parg,pengine );
	    		}
	    		if( ! planUtils.switchToPlan("receiveData").getGoon() ) break;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=waitForNumSonars WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean receiveData() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "receiveData";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??msg(E,\"event\",S,none,p(Distance,SID),N)" )) != null ){
	    		parg = "assert(tempSonar(Distance,SID))";
	    		parg = QActorUtils.substituteVars(guardVars,parg);
	    		//tout=1 day (24 h)
	    		//aar = solveGoalReactive(parg,86400000,"","");
	    		//genCheckAar(m.name)»		
	    		QActorUtils.solveGoal(parg,pengine );
	    		}
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?tempSonar(Distance,SID)" )) != null ){
	    		parg = "retract(sonar(_,SID))";
	    		parg = QActorUtils.substituteVars(guardVars,parg);
	    		//tout=1 day (24 h)
	    		//aar = solveGoalReactive(parg,86400000,"","");
	    		//genCheckAar(m.name)»		
	    		QActorUtils.solveGoal(parg,pengine );
	    		}
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?tempSonar(Distance,SID)" )) != null ){
	    		parg = "assert(sonar(Distance,SID))";
	    		parg = QActorUtils.substituteVars(guardVars,parg);
	    		//tout=1 day (24 h)
	    		//aar = solveGoalReactive(parg,86400000,"","");
	    		//genCheckAar(m.name)»		
	    		QActorUtils.solveGoal(parg,pengine );
	    		}
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?tempSonar(Distance,SID)" )) != null ){
	    		parg = "retract(lastsonarid(_))";
	    		parg = QActorUtils.substituteVars(guardVars,parg);
	    		//tout=1 day (24 h)
	    		//aar = solveGoalReactive(parg,86400000,"","");
	    		//genCheckAar(m.name)»		
	    		QActorUtils.solveGoal(parg,pengine );
	    		}
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??tempSonar(Distance,SID)" )) != null ){
	    		parg = "assert(lastsonarid(SID))";
	    		parg = QActorUtils.substituteVars(guardVars,parg);
	    		//tout=1 day (24 h)
	    		//aar = solveGoalReactive(parg,86400000,"","");
	    		//genCheckAar(m.name)»		
	    		QActorUtils.solveGoal(parg,pengine );
	    		}
	    		if( ! planUtils.switchToPlan("evaluateData").getGoon() ) break;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=receiveData WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean evaluateData() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "evaluateData";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = "\"evaluate data\"";
	    		println( temporaryStr );  
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?checkdetected" )) != null ){
	    		if( ! planUtils.switchToPlan("sendTakePicture").getGoon() ) break;
	    		}
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?checkexpression" )) != null ){
	    		if( ! planUtils.switchToPlan("alarm").getGoon() ) break;
	    		}
	    		if( planUtils.repeatPlan(0).getGoon() ) continue;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=evaluateData WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean alarm() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "alarm";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = "\"stop\"";
	    		println( temporaryStr );  
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "stop","stop", guardVars ).toString();
	    		emit( "stop", temporaryStr );
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=alarm WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean prologFailure() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "prologFailure";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = "\"prolog failure\"";
	    		println( temporaryStr );  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=prologFailure WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean sendStart() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "sendStart";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		//delay
	    		aar = delayReactive(5000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "sendStart";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "start","start", guardVars ).toString();
	    		emit( "start", temporaryStr );
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=sendStart WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean test() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "test";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		if( ! planUtils.switchToPlan("sendStart").getGoon() ) break;
	    		//delay
	    		aar = delayReactive(5000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "test";
	    		if( ! aar.getGoon() ) break;
	    		if( ! planUtils.switchToPlan("sendTakePicture").getGoon() ) break;
	    		//delay
	    		aar = delayReactive(5000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "test";
	    		if( ! aar.getGoon() ) break;
	    		if( ! planUtils.switchToPlan("sendStop").getGoon() ) break;
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=test WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean sendStop() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "sendStop";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "stop","stop", guardVars ).toString();
	    		emit( "stop", temporaryStr );
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=sendStop WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean sendTakePicture() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "sendTakePicture";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "takepicture","takepicture", guardVars ).toString();
	    		emit( "takepicture", temporaryStr );
	    		if( ! planUtils.switchToPlan("updateRadarGui").getGoon() ) break;
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=sendTakePicture WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean updateRadarGui() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "updateRadarGui";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?sonar(Distance,SID)" )) != null ){
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine,"startRadarGui(p(Distance,SID))","startRadarGui(p(Distance,SID))", guardVars ).toString();
	    		sendMsg("startRadarGui","gui_controller", QActorContext.dispatch, temporaryStr ); 
	    		}
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=updateRadarGui WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	    
	 
		/* 
		* ------------------------------------------------------------
		* APPLICATION ACTIONS
		* ------------------------------------------------------------
		*/
		/* 
		* ------------------------------------------------------------
		* QUEUE  
		* ------------------------------------------------------------
		*/
		    protected void getMsgFromInputQueue(){
	//	    	println( " %%%% getMsgFromInputQueue" ); 
		    	QActorMessage msg = mysupport.getMsgFromQueue(); //blocking
	//	    	println( " %%%% getMsgFromInputQueue continues with " + msg );
		    	this.currentMessage = msg;
		    }
	  }
	
