/* Generated by AN DISI Unibo */ 
package it.unibo.ctxControl;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evh_control extends AbstractEvh_control { 
	public Evh_control(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
