/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.control_logic;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Control_logic extends AbstractControl_logic { 
	public Control_logic(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
