/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.gui_controller;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Gui_controller extends AbstractGui_controller { 
	public Gui_controller(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
